name: flutter_riverpod_starter_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  internet_connection_checker: ^3.0.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  talker_dio_logger: ^4.8.3
  talker_riverpod_logger: ^4.8.3

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations
    - .env.dev
    - .env.staging
    - .env.prod

fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Thin.ttf
        weight: 200
      - asset: fonts/Roboto-Light.ttf
        weight: 200
      - asset: fonts/Roboto-Regular.ttf
        weight: 200
      - asset: fonts/Roboto-Medium.ttf
        weight: 300
      - asset: fonts/Roboto-Bold.ttf
        weight: 600
      - asset: fonts/Roboto-Italic.ttf
        style: italic
